### ISSUE TITLE
 RequestError: Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sedhuait** [kdelmonte/get-random-quote#1]
```

Unhandled rejection RequestError: Error: self signed certificate in certificate chain
    at new RequestError (/Users/ccc/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/ccc/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/ccc/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/ccc/node_modules/request/request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/Users/ccc/node_modules/request/request.js:878:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) 

```

**Comment by kdelmonte** [comment]
I am going to need more detail then this to be able to help you.

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @mastersilvio, @elranu, @HE07310, @guladima, @zhumj1231, @hugoxrosa, @tortuvshin
